### ISSUE TITLE
AppDF-editor: does not recognize large promotion image size (1024x500) on Windows. Works well on Mac

### ISSUE THREAD

**Issue by coolmatescomltd** [onepf/AppDF#145]
MOST URGENT appDF editor does not recognise large promotion png format images of 1024x500 pixels correctly supplied in the large promotional image upload section in yandex, chrome or firefox running under windows os.

**Comment by oorlov** [comment]
Mac: Chrome, Yandex.Browser - ok
Win: Chrome, Yandex.Browser, Firefox - says image size is wrong

**Comment by oorlov** [comment]
fixed by https://github.com/onepf/onepf.org/commit/133770f5778b9854472659a18ffd14e2d5fdb137
