### ISSUE TITLE
how about the following?

### ISSUE THREAD

**Issue by coolmatescomltd** [onepf/AppDF#146]
1. produce something that works BEFORE hyping it up and enforcing the use of the item through idiot partners who obviously joined this scheme blind, without any testing being done by you or themselves.

YOUR ONLINE APPDF EDITOR DOES NOT WORK.
1. provide proper support, instead of this crappy and useless github scheme, wherein the most urgent and important support requests are ignored for days/weeks/months(?) on end.

**Comment by oorlov** [comment]
We'd love to do it. And you are right, GitHub scheme is not designed for immediate customer support. So why not to contact me directly by email, or skype: oleg.v.orlov in urgent case? We appreciate you share AppDF production issues with us and I would love to understand what's wrong with your case and how to approach it. AppDF is just a format, so I'm sure we can find a workaround  at least if you share more details.
