### ISSUE TITLE
Editor / Importing AppDF file fails: Glob file dimensions check 

### ISSUE THREAD

**Issue by prophiterol** [onepf/AppDF#156]
Hello,

I have been following this project for the last two weeks with interest and I've been testing it on my own for a while now. I've seen that the IMPORT APPDF feature doesn't work properly. I can't manage to import a file properly as always stops on parsing. When upload is finished and the parsing starts, the process bar just freezes at 50%. In other words, when validating that the XML data fullfills AppDF specifications.

![stopsworking](https://f.cloud.github.com/assets/3465332/2216354/b38ffcf6-9a08-11e3-9b46-f87c3f7daf7a.png)

As I have found, the problem happens when validating the size of Icon and other image files included in the XML, and crashes the script with no error showing. More concretely on this function located on "appdfparser.js".

```
appdfImages.getImgSizeFromBlob(appdfXMLLoader.appdfFiles[appIconList[i].name], function(width, height) { }
```

Theoretically this function checks for the glob version of the icon to be 512x512 (same for other screenshots or images). I don't know if this validation is really needed, as just a few lines before we check the XML values corresponding to the sizes of the image (512x512). Surely these values can be different if the AppDF file has been tampered manually, but I would say almost 100% of the XMLs will (should) contain already the correct image sizes of the referenced images.

Anyway, I just wanted to point out that this piece of code doesn't work at the moment. Commenting it out, leaving only the "onend([]);" statement solves it problem, and per the exposed above is not likely to have any further issues as the size would be set explicitly on the xml.

Oh, and great job guys. This is one of the most interesting projects out there at the moment. Cheers!

**Comment by oorlov** [comment]
Thanks for pointing to a function.  Editor really looks sick when it tries to import something, so we are going to fix it soon :)
