### ISSUE TITLE
Which language should we use for the parser/validator library?

### ISSUE THREAD

**Issue by vassiliphilippov** [onepf/AppDF#17]
What this library should do:
- Extracting the files from ZIP archive
- Check description.xml validity
- Parse description.xml file and present it as an easy to use structure
- Check APK files vavility
- Extract information from APK files
- Check that all the files mentioned in the description.xml are presented in the ZIP archive
- Resize the images to the needed resolution

Where this library will be used:
- By appstores for parsing AppDF files as a reference implementation
- In our online validation tool

So the question is: which language should we use for this parser/validator library?

**Comment by thevery** [comment]
this library will be used only server-side or client-side also?

**Comment by ymkawb** [comment]
I suppose both, so multiple implementations should be handy ( at least JVM and .NET based)

**Comment by vassiliphilippov** [comment]
I start to think that Java will be the best choice. First, Java is Android favourite language, so it will be well understood and supported by Android community. Second there are existing Java libraries for parsing APK files.

**Comment by vassiliphilippov** [comment]
Resolution: we will create parsers in several languages. Our main parser will be in Java, second priority: PHP.
