### ISSUE TITLE
What should be interface of Java library to parse/validate/create AppDF files?

### ISSUE THREAD

**Issue by vassiliphilippov** [onepf/AppDF#28]
Our main library for AppDF file support will be in Java. It should support the following functionality:
- Creating AppDF file (will be used in our website for AppDF file generating)
- Parsing AppDF files (will be used by appstores for parsing submitted AppDF files)
- AppDF file validation (will be used by our online validator tool)

Couple of questions about the library structure:
1. What should be top level library interface (classes/interfaces/main methods)?
2. What are similar Java libraries? For creating/parsing some format files with package structure and a description file?
3. Should we merge creating/parsing functionality in one class?

**Comment by ymkawb** [comment]
android command line is good example AFAIK. Should it be one library or several (craeor-validator-parsing) we should really think about simple usage of such libraries in server side stores

**Comment by ymkawb** [comment]
More over are we sure that java only is a good apporach? What CMSs are most stores are based upon?

**Comment by vassiliphilippov** [comment]
Why Android command line is a good example? We need code that will be linked to the store code not a command line tool.

We will start with Java library, it will be much easier for us to create it in Java than any other language and Java is "good enough" for the purposes we have.

**Comment by ymkawb** [comment]
Command line options look ok for creation pursposes ( create AppDF file with default values for existing project and inflate some values from project AndroidManifest.xml )

**Comment by vassiliphilippov** [comment]
Resolution: we will create a parser project, @ymkawb will create an interface for it
