### ISSUE TITLE
Create reference C++ code for parsing AppDF files

### ISSUE THREAD

**Issue by vassiliphilippov** [onepf/AppDF#4]

**Comment by thevery** [comment]
Java is more preferred for server-side I think

**Comment by vassiliphilippov** [comment]
I think most appstores are created using PHP/Python. Do you think that using Java code from PHP or Python is easier than using C++ code?

**Comment by thevery** [comment]
Not sure about php/python, but I don't have any exact information.
Java code is easier to read than C++, but for simple DOM parser is might be not so important.
Another option is convertor tool from AppDF XML to some cross-platform format like protobuf.

**Comment by shtirlic** [comment]
Libxml2 is the XML C parser + C parser, so it's will be possible to use everywhere (as native extenseion).
PS
C and Java code would be ok for everything

**Comment by vassiliphilippov** [comment]
We will create reference parsers in several languages but the first would be Java.
