### ISSUE TITLE
Add copyright and license to XSD

### ISSUE THREAD

**Issue by vassiliphilippov** [onepf/AppDF#41]

**Comment by ymkawb** [comment]
Should we also include license information to java source files?

**Comment by vassiliphilippov** [comment]
Yes

Nikolay Ivanov notifications@github.com написал(а):

> Should we also include license information to java source files? 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/onepf/AppDF/issues/41#issuecomment-12242438

## 

Отправлено через К-9 Mail. Извините за краткость, пожалуйста.
