### ISSUE TITLE
Create a JavaScript webpage where you can submit all your application info and it will generate AppDF file

### ISSUE THREAD

**Issue by vassiliphilippov** [onepf/AppDF#6]
Let's try to go with client-side only JavaScript code. 

A good example how such technology could work is here:
http://android-ui-utils.googlecode.com/hg/asset-studio/dist/index.html

**Comment by vassiliphilippov** [comment]
Seems like a useful link:
http://viralpatel.net/blogs/create-zip-file-javascript/

**Comment by vassiliphilippov** [comment]
Current version under development could be found at:
https://github.com/onepf/AppDF/tree/master/tools/editor/js

**Comment by friedger** [comment]
Could you develop it in branch gh-pages? Or make copy from time to time to this branch, such that there is a live version on github pages?
