### ISSUE TITLE
Create AppDF validator

### ISSUE THREAD

**Issue by vassiliphilippov** [onepf/AppDF#7]

**Comment by thevery** [comment]
maybe at least xsd schema if we use XML?

**Comment by vassiliphilippov** [comment]
XSD scheme is a good first step but it is not enough. You cannot check with XSD scheme ZIP content, that there are file with right names, that they have right types, that screenshots have right sizes, etc.

**Comment by thevery** [comment]
another option: make zip package tool with validation feature.

**Comment by vassiliphilippov** [comment]
Validator will be a part of the parser. So after the parser is created it will be easy to create a web service for AppDF validation. Will reopen this task after the parser is ready
